name: Test build of KVM-QEMU

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: |
    chmod a+x "${GITHUB_WORKSPACE}/Virtualization/kvm-qemu.sh"
    "${GITHUB_WORKSPACE}/Virtualization/kvm-qemu.sh all"
