on:
  push:
    branch:
      - master

name: Test build of KVM-QEMU

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
      chmod a+x "${GITHUB_WORKSPACE}/Virtualization/kvm-qemu.sh"
      "${GITHUB_WORKSPACE}/Virtualization/kvm-qemu.sh all"
