on:
  push:
    branch:
      - master

name: Test build of KVM-QEMU

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod a+x "${GITHUB_WORKSPACE}/Virtualization/kvm-qemu.sh"
         ls -lah *
         "${GITHUB_WORKSPACE}/Virtualization/kvm-qemu.sh all"
      shell: bash
